url: http://dcassol.com/
baseurl:

# Site Settings
title: Daniela Cassol
description: "dcassol web page"
keywords: "dcassol"
google-tracking-id:

# Career Settings
# Default career thumbnail image.
career-img: "img/timeline/daniCassol.jpg"

exclude: ["Rakefile", "readme.markdown"]
